# Generated by Django 5.2.1 on 2025-08-21 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='deafult_avatar_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
