# Generated by Django 5.2.1 on 2025-10-30 21:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_customuser_deafult_avatar_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='currency',
            field=models.IntegerField(default=1000),
        ),
    ]
