# Generated by Django 5.2.1 on 2025-11-16 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_customuser_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='karma',
        ),
    ]
