# Generated by Django 5.2.1 on 2025-11-16 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_remove_customuser_karma'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='bio',
            field=models.TextField(blank=True, default='Hi There, I am a Vera User!', null=True),
        ),
    ]
