# Generated by Django 5.2.1 on 2025-08-21 18:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('resolution_date', models.DateTimeField()),
                ('resolved', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('completed', models.BooleanField(default=False)),
                ('receiver_confirmed', models.BooleanField(default=False)),
                ('stake_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('dispute_open', models.BooleanField(default=False)),
                ('giver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises_given', to=settings.AUTH_USER_MODEL)),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises_received', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
