# Generated by Django 5.2.1 on 2025-11-23 16:59

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Promise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.TextField()),
                ('description', models.TextField()),
                ('resolution_date', models.DateTimeField()),
                ('stake_amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('resolved', models.BooleanField(default=False)),
                ('completed', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('dispute_open', models.BooleanField(default=False)),
                ('majority_vote', models.BooleanField(default=False)),
                ('failed', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='PromiseReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
    ]
