# Generated by Django 5.2.1 on 2025-11-23 16:59

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('promises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='giver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promises_given', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promisereceiver',
            name='promise',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promise_receivers', to='promises.promise'),
        ),
        migrations.AddField(
            model_name='promisereceiver',
            name='receiver',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='promise',
            name='receivers',
            field=models.ManyToManyField(related_name='promises_received', through='promises.PromiseReceiver', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterUniqueTogether(
            name='promisereceiver',
            unique_together={('promise', 'receiver')},
        ),
    ]
