# Generated by Django 5.2.1 on 2025-10-22 16:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RemoveField(
            model_name='promise',
            name='receiver',
        ),
        migrations.RemoveField(
            model_name='promise',
            name='receiver_confirmed',
        ),
        migrations.CreateModel(
            name='PromiseReceiver',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('accepted', models.BooleanField(default=False)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('promise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='promise_receivers', to='promises.promise')),
                ('receiver', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('promise', 'receiver')},
            },
        ),
        migrations.AddField(
            model_name='promise',
            name='receivers',
            field=models.ManyToManyField(related_name='promises_received', through='promises.PromiseReceiver', to=settings.AUTH_USER_MODEL),
        ),
    ]
