# Generated by Django 5.2.1 on 2025-11-16 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_remove_promise_receiver_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='majority_vote',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='promise',
            name='title',
            field=models.TextField(default='No Title'),
            preserve_default=False,
        ),
    ]
