# Generated by Django 5.2.1 on 2025-11-23 23:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='promisereceiver',
            name='complete',
            field=models.BooleanField(default=False),
        ),
    ]
