# Generated by Django 5.2.1 on 2025-11-16 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0003_promise_majority_vote_promise_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='failed',
            field=models.BooleanField(default=False),
        ),
    ]
