# Generated by Django 5.2.1 on 2025-11-24 00:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('promises', '0003_promisereceiver_complete'),
    ]

    operations = [
        migrations.AddField(
            model_name='promise',
            name='started',
            field=models.BooleanField(default=False),
        ),
    ]
